name: Bgm-Data-Sync
on:
  # Schedule daily updates
  schedule: [{ cron: '0 0 * * *' }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: 生成收藏卡片任务
    steps:
      - name: Bgm Collection Card
        id: bgm
        uses: xiaoyvyv/bangumi-action@v1.1.14
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'xiaoyvyv'
          bgm-img-path: 'bgm/card.svg'
          
      - name: Get the output message
        run: echo "The message was ${{ steps.bgm.outputs.message }}"
