name: bgm-syncer
on:
  # 每日零点执行（这个配置最小间隔5分钟）
  schedule: [{ cron: '0 0 * * *' }]
  # 手动触发
  workflow_dispatch:
  # master/main 分支有提交时执行
  push: {branches: ["master", "main"]}

jobs:
  bgm-sync:
    runs-on: ubuntu-latest
    name: 每日同步BGM收藏卡片
    steps:
      - name: Bgm Collection Card
        id: bgm
        uses: xiaoyvyv/bangumi-action@v1.1.17
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'xiaoyvyv'
          bgm-img-path: 'data/bgm/card.svg'

      - name: Get the output image url
        run: echo "图片生成的链接地址 ${{ steps.bgm.outputs.message }}"
        
  mikan-sync:
    runs-on: ubuntu-latest
    name: 每日同步蜜柑计划的ID映射表
    steps:
      - name: sync mikan id-map
        id: mikan
        uses: xiaoyvyv/bangumi-mikan@v1.0.4
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          mikan-json-path: 'data/mikan/bangumi-mikan.json'

      - name: Get the output file url
        run: echo "上传地址 ${{ steps.mikan.outputs.message }}"
