on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Bgm Collection Card
        id: bgm
        uses: xiaoyvyv/bangumi-action@v1.1.12
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'xiaoyvyv'
          bgm-img-path: 'bgm/card.svg'
          
      - name: Get the output message
        run: echo "The message was ${{ steps.bgm.outputs.message }}"
