name: bgm-syncer
on:
  # 每日零点执行（这个配置最小间隔5分钟）
  schedule: [{ cron: '0 0 * * *' }]
  # 手动触发
  workflow_dispatch:
  # master/main 分支有提交时执行
  push: {branches: ["master", "main"]}

jobs:
  bgm-sync:
    runs-on: ubuntu-latest
    name: 每日同步 Bangumi.TV 相关数据任务
    steps:
      - name: 更新 Bangumi.TV 收藏卡片
        id: bgm
        uses: xiaoyvyv/bangumi-action@v1.1.19
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'xiaoyvyv'
          bgm-img-path: 'data/bgm/card.svg'
          
      - name: 更新蜜柑计划 ID 映射表
        id: mikan
        uses: xiaoyvyv/bangumi-mikan@v1.0.5
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          mikan-json-path: 'data/mikan/bangumi-mikan.json'

      - name: 获取输出结果
        run: echo "收藏卡片地址 ${{ steps.bgm.outputs.message }}，蜜柑映射表地址 ${{ steps.mikan.outputs.message }}"
